### ISSUE TITLE
Budon vs Budron Typo in vesseldata.xml

### ISSUE THREAD

**Issue by Sheltari** [tsnrp/mod#5]
<hullRace ID="21" name="Budon" keys="FactionBudron">
    <taunt immunity="is known to soak daily" text="You are lookng a bit prunish!"/>
    <taunt immunity="Has a first in digestive chemistry" text="Was that deliberate or did you just fart and explode half your crew?"/>
    <taunt immunity="Is mild-mannered" text="Hey, you need to take a chill pill"/>
  </hullRace>

Could be corrected to:

	  <hullRace ID="21" name="Budron" keys="FactionBudron">
    <taunt immunity="is known to soak daily" text="You are looking a bit prunish!"/>
    <taunt immunity="Has a first in digestive chemistry" text="Was that deliberate, or did you just fart and explode half your crew?"/>
    <taunt immunity="Is mild-mannered" text="Hey, you need to take a chill pill."/>
  </hullRace>

**Comment by astrolamb-gaming** [comment]
Yep, thanks, it's been bugging me lol
https://github.com/tsnrp/mod-development/issues/23

**Comment by astrolamb-gaming** [comment]
See https://github.com/tsnrp/mod/pull/4
