### ISSUE TITLE
Arvonian Fighter Wing: .dxs and .xml scale corrections to resolve silhouette collisions

### ISSUE THREAD

**Issue by Sheltari** [tsnrp/mod#6]
Credit to UE & Starry for their assistance in diagnosing and testing this issue for our own records.

There's an issue in Artemis where .dxs models beyond certain dimensions (ballpark threshold is somewhere between ~850-1,000) will have their silhouettes "trimmed," and those trimmings will be drawn onto other ship silhouettes. We believe this is likely to be a side effect of the way in which Artemis generates these silhouettes as an optimization measure, whereby all the ships are assembled a set distance apart, from a dorsal perspective, across a single image. This "grid" of silhouettes likely does not account for the dimensions of the .dxs files it references, which can result in oversized assets spilling into other assets' allotted areas. While there is still a measure of uncertainty in how this silhouette grid may be assembled, if it does exist, tests involving drastic changes to ship scales seems to support this hypothesis.

All this to say that the present Avornian Fighter Wing model is over that dimension threshold, and is drawing onto other silhouettes while having its own trimmed. The fix is easy enough; the consequences of the fix are more of an issue. Since the silhouettes are drawn using the .dxs, its scale from Science, Helm, and the like will be reduced and possibly less distinct as a result. The greater problem is that the Manual Beam view may use the .dxs dimensions as well, making for a smaller target in manual beams. Issues aside, the proposed fix is as follows:

Replace the existing .dxs with the following (restricted access link):
https://drive.google.com/file/d/1Z-uNe_JKXoA8pAajptJVqn_jAs-OLw2p/view?usp=sharing

Replace the existing vesseldata entry with the following (restricted access link):
https://drive.google.com/file/d/1ydsbKtfyZAcmK0NfJxJGIdSVqn7q25vB/view?usp=sharing

**Comment by XavierWise** [comment]
Add data and dxs file to Mod 3.0
